apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: catalog-dependent-service-b
  description: Fake dependent service
spec:
  owner: dx
  type: service
  lifecycle: production
  system: example
